# Generated by Django 5.2.8 on 2025-12-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=20000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='risk_appetite',
            field=models.CharField(choices=[('LOW', 'Conservative'), ('MID', 'Moderate'), ('HIGH', 'Agrressive')], default='MID', max_length=20),
        ),
    ]
