# Generated by Django 5.2.8 on 2025-12-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('MF', 'Mutual Fund'), ('ETF', 'ETF'), ('CRYPTO', 'Crypto'), ('GOLD', 'Gold/Silver'), ('REIT', 'REIT')], default='STOCK', max_length=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='market_cap_category',
            field=models.CharField(choices=[('LARGE', 'Large Cap'), ('MID', 'Mid Cap'), ('SMALL', 'Small Cap')], default='MID', max_length=10),
        ),
    ]
