# Generated by Django 5.2.8 on 2025-12-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_asset_asset_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
